In [4]:
# 创建一个numpy数组对象arr
import numpy as np 

arr = np.array([1, 2, 3, 4, 5])
print(arr)
print(type(arr))

# 多于一个维度  
import numpy as np 
a = np.array([[1,  2],  [3,  4]])  
print (a)

# 最小维度  
import numpy as np 
a = np.array([1, 2, 3, 4, 5], ndmin =  2)  
print (a)

# dtype 参数  
import numpy as np 
# 复数形式
a = np.array([1,  2,  3], dtype = complex)  
print (a)

[1 2 3 4 5]
<class 'numpy.ndarray'>
[[1 2]
 [3 4]]
[[1 2 3 4 5]]
[1.+0.j 2.+0.j 3.+0.j]


In [6]:
# 数据类型
import numpy as np
# 自定义数据类型student
student = np.dtype([('name','S20'), ('age', 'i1'), ('marks', 'f4')]) 
# 创建numpy对象数组，使用student数据类型
a = np.array([('abc', 21, 50),('xyz', 18, 75)], dtype = student) 
print(a)

[(b'abc', 21, 50.) (b'xyz', 18, 75.)]


In [12]:
# 数组属性
import numpy as np 

 # ndarray.ndim 用于返回数组的维数，等于秩。
a = np.arange(24)  
print (a.ndim)             # a 现只有一个维度
# 现在调整其大小
b = a.reshape(2,4,3)  # b 现在拥有三个维度
print (b.ndim)

# ndarray.shape 表示数组的维度，返回一个元组，这个元组的长度就是维度的数目，即 ndim 属性(秩)。
# 2行3列
a = np.array([[1,2,3],[4,5,6]])  
print (a.shape)
# 调整数组大小为3行2列
a = np.array([[1,2,3],[4,5,6]]) 
a.shape =  (3,2)  
print (a)

# ndarray.itemsize 以字节的形式返回数组中每一个元素的大小。
# 数组的 dtype 为 int8（一个字节）  
x = np.array([1,2,3,4,5], dtype = np.int8)  
print (x.itemsize)

# ndarray.flags 返回 ndarray 对象的内存信息
x = np.array([1,2,3,4,5])  
print (x.flags)

1
3
(2, 3)
[[1 2]
 [3 4]
 [5 6]]
1
  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False



In [14]:
# 创建数组
# numpy.zeros 创建指定大小的数组，数组元素以 0 来填充
# numpy.zeros(shape, dtype = float, order = 'C')
z = np.zeros((2,2), dtype = [('x', 'i4'), ('y', 'i4')])  
print(z)

# numpy.ones 创建指定大小的数组，数组元素以 1 来填充
x = np.ones([2,2], dtype = int)
print(x)

[[(0, 0) (0, 0)]
 [(0, 0) (0, 0)]]
[[1 1]
 [1 1]]
