In [4]:
# 创建一个numpy数组对象arr
import numpy as np 

arr = np.array([1, 2, 3, 4, 5])
print(arr)
print(type(arr))

# 多于一个维度  
import numpy as np 
a = np.array([[1,  2],  [3,  4]])  
print (a)

# 最小维度  
import numpy as np 
a = np.array([1, 2, 3, 4, 5], ndmin =  2)  
print (a)

# dtype 参数  
import numpy as np 
# 复数形式
a = np.array([1,  2,  3], dtype = complex)  
print (a)

[1 2 3 4 5]
<class 'numpy.ndarray'>
[[1 2]
 [3 4]]
[[1 2 3 4 5]]
[1.+0.j 2.+0.j 3.+0.j]


In [6]:
# 数据类型
import numpy as np
# 自定义数据类型student
student = np.dtype([('name','S20'), ('age', 'i1'), ('marks', 'f4')]) 
# 创建numpy对象数组，使用student数据类型
a = np.array([('abc', 21, 50),('xyz', 18, 75)], dtype = student) 
print(a)

[(b'abc', 21, 50.) (b'xyz', 18, 75.)]


In [12]:
# 数组属性
import numpy as np 

 # ndarray.ndim 用于返回数组的维数，等于秩。
a = np.arange(24)  
print (a.ndim)             # a 现只有一个维度
# 现在调整其大小
b = a.reshape(2,4,3)  # b 现在拥有三个维度
print (b.ndim)

# ndarray.shape 表示数组的维度，返回一个元组，这个元组的长度就是维度的数目，即 ndim 属性(秩)。
# 2行3列
a = np.array([[1,2,3],[4,5,6]])  
print (a.shape)
# 调整数组大小为3行2列
a = np.array([[1,2,3],[4,5,6]]) 
a.shape =  (3,2)  
print (a)

# ndarray.itemsize 以字节的形式返回数组中每一个元素的大小。
# 数组的 dtype 为 int8（一个字节）  
x = np.array([1,2,3,4,5], dtype = np.int8)  
print (x.itemsize)

# ndarray.flags 返回 ndarray 对象的内存信息
x = np.array([1,2,3,4,5])  
print (x.flags)

1
3
(2, 3)
[[1 2]
 [3 4]
 [5 6]]
1
  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False



In [16]:
# 创建数组
# numpy.zeros 创建指定大小的数组，数组元素以 0 来填充
# numpy.zeros(shape, dtype = float, order = 'C')
z = np.zeros((2,2), dtype = [('x', 'i4'), ('y', 'i4')])  
print(z)

# numpy.ones 创建指定大小的数组，数组元素以 1 来填充
x = np.ones([2,2], dtype = int)
print(x)

# numpy.zeros_like 创建一个与给定数组具有相同形状的数组，数组元素以 0 来填充
# numpy.ones_like 同理，用1填充
# 创建一个 3x3 的二维数组
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
 
# 创建一个与 arr 形状相同的，所有元素都为 0 的数组
zeros_arr = np.zeros_like(arr)
print(arr)
print(zeros_arr)

[[(0, 0) (0, 0)]
 [(0, 0) (0, 0)]]
[[1 1]
 [1 1]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [35]:
# 从已有的数组创建数组

import numpy as np 
 
x =  [(1,1,5),(2,2,5),(3,3,5)] 
# numpy.asarray(a, dtype = None, order = None)
a = np.asarray(x, dtype =  float, order = 'F')  
print (a)

# numpy.frombuffer 接受 buffer 输入参数，以流的形式读入转化成 ndarray 对象。
import numpy as np 
 
s =  b'Hello World' 
a = np.frombuffer(s, dtype =  'S1')  
print (a)

# numpy.fromiter 方法从可迭代对象中建立 ndarray 对象，返回一维数组。
import numpy as np 
 
# 使用 range 函数创建列表对象  
list=range(5)
it=iter(list)
 
# 使用迭代器创建 ndarray 
x=np.fromiter(it, dtype=float)
print(x)

[[1. 1. 5.]
 [2. 2. 5.]
 [3. 3. 5.]]
[b'H' b'e' b'l' b'l' b'o' b' ' b'W' b'o' b'r' b'l' b'd']
[0. 1. 2. 3. 4.]


In [50]:
# 从数值范围上创建数组

# numpy 包中的使用 arange 函数创建数值范围并返回 ndarray 对象
# numpy.arange(start, stop, step, dtype)
# 设置了起始、终点和步长
import numpy as np
x = np.arange(10,20,2)  
print (x)

# numpy.linspace 函数用于创建一个一维数组，数组是一个等差数列构成的
# np.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None)
import numpy as np
x = np.linspace(10,30,5,endpoint=True,retstep=True)
print(x)

# numpy.logspace 函数用于创建一个于等比数列
# np.logspace(start, stop, num=50, endpoint=True, base=10.0, dtype=None)
import numpy as np
x = np.logspace(1,10,num = 10,base = 2)
print(x)

[10 12 14 16 18]
(array([10., 15., 20., 25., 30.]), 5.0)
[   2.    4.    8.   16.   32.   64.  128.  256.  512. 1024.]


In [54]:
# NumPy 切片和索引
# 切片对象可以通过内置的 slice 函数，并设置 start, stop 及 step 参数进行，从原数组中切割出一个新数组。
import numpy as np

a = np.arange(10)
# 从索引2到7切割，步长为2
s = slice(2,7,2)
print (a[s])

# 多维数组也一样
import numpy as np
 
a = np.array([[1,2,3],[3,4,5],[4,5,6]])
print(a)  
print (a[...,1])   # 第2列元素
print (a[1,...])   # 第2行元素
print (a[...,1:])  # 第2列及剩下的所有元素

[2 4 6]
[[1 2 3]
 [3 4 5]
 [4 5 6]]
[2 4 5]
[3 4 5]
[[2 3]
 [4 5]
 [5 6]]


In [67]:
# 高级索引
# 整数数组索引
import numpy as np 
 
x = np.array([[  0,  1,  2],[  3,  4,  5],[  6,  7,  8],[  9,  10,  11]])  
print ('我们的数组是：' )
print (x)
print ('\n')
# 行索引是[0,0]和[3,3]
rows = np.array([[0,0],[3,3]]) 
# 列索引是 [0,2] 和 [0,2]
cols = np.array([[0,2],[0,2]]) 
# [0,0],[0,2],[3,0],[3,2]
y = x[rows,cols]  
print  ('这个数组的四个角元素是：')
print (y)

# 可以借助切片 : 或 … 与索引数组组合。
import numpy as np
 
a = np.array([[1,2,3], [4,5,6],[7,8,9]])
print('\n')
print(a)
# rows索引1-3，cols索引1-3
b = a[1:3, 1:3]
c = a[1:3,[1,2]]
d = a[...,1:]
print(b)
print(c)
print(d)

# 布尔索引
import numpy as np 
 
x = np.array([[  0,  1,  2],[  3,  4,  5],[  6,  7,  8],[  9,  10,  11]])  
print ('我们的数组是：')
print (x)
print ('\n')
# 现在我们会打印出大于 5 的元素  
print  ('大于 5 的元素是：')
print (x[x >  5])

# 过滤掉非复数
import numpy as np 
 
a = np.array([1,  2+6j,  5,  3.5+5j])  
print (a[np.iscomplex(a)])

# 二维数组索引
import numpy as np 
 
x=np.arange(32).reshape((8,4))
print(x)
# 二维数组读取指定下标对应的行
print("-------读取下标对应的行-------")
print (x[[4,2,1,7]])


# 笛卡尔乘积
import numpy as np 
 
x=np.arange(32).reshape((8,4))
print (x[np.ix_([1,5,7,2],[0,3,1,2])])

我们的数组是：
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


这个数组的四个角元素是：
[[ 0  2]
 [ 9 11]]


[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[5 6]
 [8 9]]
[[5 6]
 [8 9]]
[[2 3]
 [5 6]
 [8 9]]
我们的数组是：
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


大于 5 的元素是：
[ 6  7  8  9 10 11]
[2. +6.j 3.5+5.j]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]
-------读取下标对应的行-------
[[16 17 18 19]
 [ 8  9 10 11]
 [ 4  5  6  7]
 [28 29 30 31]]
[[ 4  7  5  6]
 [20 23 21 22]
 [28 31 29 30]
 [ 8 11  9 10]]


In [2]:
# NumPy 广播
import numpy as np 

 # 满足a.shape == b.shape，则a*b = 对应位置的乘积
a = np.array([1,2,3,4]) 
b = np.array([10,20,30,40]) 
c = a * b 
print (c)

# 而当shape不同时，触发广播机制，每行都与一维b数组相加，b数组自动向下补齐为4行。
a = np.array([[ 0, 0, 0],
           [10,10,10],
           [20,20,20],
           [30,30,30]])
b = np.array([0,1,2])
print(a + b)

[ 10  40  90 160]
[[ 0  1  2]
 [10 11 12]
 [20 21 22]
 [30 31 32]]


In [8]:
# NumPy 迭代数组
import numpy as np
 
a = np.arange(6).reshape(2,3)
print ('原始数组是：')
print (a)
print ('\n')
print ('迭代输出元素：')
# 使用nditer迭代
for x in np.nditer(a):
    print (x, end=", " )
print ('\n')
# 列优先
print(a.T)
# copy(order='C')默认按行访问
for x in np.nditer(a.T.copy(order='C')):
    print (x, end=", " )
print ('\n')

#
a = np.arange(0,60,5) 
a = a.reshape(3,4)  
print ('原始数组是：') 
print (a) 
print ('\n') 
print ('原始数组的转置是：') 
b = a.T 
print (b) 
print ('\n') 
# C为行优先
print ('以 C 风格顺序排序：') 
c = b.copy(order='C')  
print (c)
for x in np.nditer(c):  
    print (x, end=", " )
print  ('\n') 
# F为列优先
print  ('以 F 风格顺序排序：')
c = b.copy(order='F')  
print (c)
for x in np.nditer(c):  
    print (x, end=", " )

原始数组是：
[[0 1 2]
 [3 4 5]]


迭代输出元素：
0, 1, 2, 3, 4, 5, 

[[0 3]
 [1 4]
 [2 5]]
0, 3, 1, 4, 2, 5, 

原始数组是：
[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]


原始数组的转置是：
[[ 0 20 40]
 [ 5 25 45]
 [10 30 50]
 [15 35 55]]


以 C 风格顺序排序：
[[ 0 20 40]
 [ 5 25 45]
 [10 30 50]
 [15 35 55]]
0, 20, 40, 5, 25, 45, 10, 30, 50, 15, 35, 55, 

以 F 风格顺序排序：
[[ 0 20 40]
 [ 5 25 45]
 [10 30 50]
 [15 35 55]]
0, 5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 